language: node_js
node_js:
- stable
branches:
  only:
  - dev
jobs:
  include:
    - stage: test
      script: npm test
    - stage: building
      before_install: bash scripts/install.sh
      env:
        - REMOTE_PATH=cookbook
        - REMOTE_USER=travisci
        - REMOTE_HOST=165.22.77.10
        - REMOTE_PORT=22
      script: 
        - npm run ts
      after_success: bash scripts/deploy.sh