language: node_js
node_js:
- stable
branches:
  only:
  - dev
jobs:
  include:
    - stage: test
      script: npm test
    - stage: building
      script:
        before_install: bash scripts/install.sh
      env:
        - REMOTE_PATH=Uploads
        - REMOTE_USER=deploy
        - REMOTE_HOST=167.172.168.233
      script: 
        - npm run ts
        - bash scripts/deploy.sh 