version: '1.0'
services:
  db:
    image: mongo:3.4.23-xenial
    volumes:
      - dbdata:/var/lib/mongodb
    restart: always
    environment:
      - MONGO_INITDB_DATABASE: mongodb
      - MONGO_INITDB_ROOT_USERNAME: mongodb
      - MONGO_INITDB_ROOT_PASSWORD: mongodb
  node:
    depends_on:
      - db
    image: node:12.13.0-alpine
    ports:
      - 8008:80
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  nginx:
    image: nginx:1.17.5
    ports:
      - 8008:80
    restart: always
    volumes: 
      - /usr/share/nginx/html 
volumes:
dbdata: